---
- hosts: all
  tasks:
      - user:
          name: tony
          state: present
          password: "{{ redhat | password_hash('sha512') }}"

      - user:
          name: harry
          state: preent
          password: "{{ redhat | password_hash('sha512') }}"

