---
- hosts: all
  tasks:
      - yum:
          name: httpd
          state: present

      - service: 
          name: httpd
          state: started
          enabled: yes

      - copy:
          dest: /var/www/html/index.html
          content: "welcome"
        notify: restart httpd
     

  handlers:
      - name: restart httpd
        service: 
               name: httpd
               state: restarted 
